spring:
  application:
    name: pizza-api-gateway
server:
  port: 8762
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  routes:
    pizza:
      service-id: pizza-builder-service
